carproject/carproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newapp.urls', namespace='cars')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders'))

]

carproject/newapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import CarsView,MyCarsDetailView,AboutUs
app_name = 'cars'

urlpatterns = [
    path('', CarsView.as_view(), name='index'),
    path('detail/<int:pk>/', MyCarsDetailView.as_view(), name = 'detail_car' ),
    path('about/', AboutUs.as_view(), name='about')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carproject/orders/urls.py
from django.urls import path
from .views import (
    ReservView,
    AddReservItemView,
    DeleteReservItemView,

    OrderConfirmationView,
    AddOrderView,
    ListOrderView,
    OrderDetailView
)

app_name = 'orders'

urlpatterns = [
    path('reserv/', ReservView.as_view(), name='reserv'),
    path('reserv/add_item/<int:pk>/', AddReservItemView.as_view(), name='add_reserv_item'),
    path('reserv/delete_item/<int:pk>/', DeleteReservItemView.as_view(), name='delete_reserv_item'),
    path('order/order_confirmation/', OrderConfirmationView.as_view(), name='order_confirmation'),
    path('order/add_order/', AddOrderView.as_view(), name='add_order'),
    path('orders/', ListOrderView.as_view(), name='orders'),
    path('orders/detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail')
]

carproject/users/urls.py
from django.urls import path
from .views import LogoutUserView,LoginUserView,RegistrationUserView,ProfileView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutUserView.as_view(), name='logout' ),
    path('login/', LoginUserView.as_view(), name='login' ),
    path('registration/', RegistrationUserView.as_view(), name='registration' ),
    path('profile/', ProfileView.as_view(), name='profile')


]

carproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<!--    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>-->

</head>
<body data-bs-theme="dark">

{% for message in messages %}
<div class="alert
    {% if message.level == 10 %}alert-success
    {% elif message.level == 40 %}alert-danger
    {% endif %}
    alert-dismissible fade show"
    role="alert">
    {{ message }}
</div>
{% endfor %}

{% include 'navbar.html' %}


{% block content %}
{% endblock %}

</body>
</html>

carproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
    <div class="container px-4">
        <a class="navbar-brand" href="{% url 'cars:index' %}">Best Car Reservation</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}"
                        href="{% url 'cars:index' %}">Cars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}"
                        href="{% url 'cars:about' %}">About Us</a>
                </li>
            </ul>

            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                        <li class="dropdown-item"><strong>Superuser: {{ user.is_superuser }}</strong></li>
                        <li class="dropdown-item"><strong>Staff: {{ user.is_staff }}</strong></li>
                        <li><hr class="dropdown-divider"></li>

                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">My Profile</a></li>

                        {% if user.is_superuser or user.is_staff %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Panel</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'orders:orders' %}">My Orders</a></li>
                        <li><a class="dropdown-item" href="{% url 'orders:reserv' %}">My Reservations</a></li>
                        {% endif %}

                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <form action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="dropdown-item" type="submit">Logout</button>
                            </form>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:registration' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


<style>
    body {
        padding-top: 80px; /* Adjust for fixed navbar */
    }
</style>